name: Tag on MR merge
on:
  push:
    branches:
      - main
      - test-github-action
jobs:
  Release-Tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Release new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # run script
          # TODO - Figure out how to use the MR to pass through whether version should be major/minor/patch
          # For now - just hardcode patch
          "${GITHUB_WORKSPACE}/tag.sh" -v patch
